/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PitchRouteImport } from './routes/pitch'
import { Route as LogoRouteImport } from './routes/logo'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as DesignsRouteImport } from './routes/designs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as ISplatRouteImport } from './routes/i.$'
import { Route as DocsSplatRouteImport } from './routes/docs.$'
import { Route as DesignsSlugRouteImport } from './routes/designs.$slug'
import { Route as AliasSplatRouteImport } from './routes/$alias.$'

const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchRoute = PitchRouteImport.update({
  id: '/pitch',
  path: '/pitch',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoRoute = LogoRouteImport.update({
  id: '/logo',
  path: '/logo',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignsRoute = DesignsRouteImport.update({
  id: '/designs',
  path: '/designs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ISplatRoute = ISplatRouteImport.update({
  id: '/i/$',
  path: '/i/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsRoute,
} as any)
const DesignsSlugRoute = DesignsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DesignsRoute,
} as any)
const AliasSplatRoute = AliasSplatRouteImport.update({
  id: '/$alias/$',
  path: '/$alias/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/designs': typeof DesignsRouteWithChildren
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRouteWithChildren
  '/downloads': typeof DownloadsRoute
  '/logo': typeof LogoRoute
  '/pitch': typeof PitchRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/$alias/$': typeof AliasSplatRoute
  '/designs/$slug': typeof DesignsSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/i/$': typeof ISplatRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/designs': typeof DesignsRouteWithChildren
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRouteWithChildren
  '/downloads': typeof DownloadsRoute
  '/logo': typeof LogoRoute
  '/pitch': typeof PitchRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/$alias/$': typeof AliasSplatRoute
  '/designs/$slug': typeof DesignsSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/i/$': typeof ISplatRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/designs': typeof DesignsRouteWithChildren
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRouteWithChildren
  '/downloads': typeof DownloadsRoute
  '/logo': typeof LogoRoute
  '/pitch': typeof PitchRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/$alias/$': typeof AliasSplatRoute
  '/designs/$slug': typeof DesignsSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/i/$': typeof ISplatRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/designs'
    | '/developers'
    | '/docs'
    | '/downloads'
    | '/logo'
    | '/pitch'
    | '/pricing'
    | '/products'
    | '/$alias/$'
    | '/designs/$slug'
    | '/docs/$'
    | '/i/$'
    | '/u/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/designs'
    | '/developers'
    | '/docs'
    | '/downloads'
    | '/logo'
    | '/pitch'
    | '/pricing'
    | '/products'
    | '/$alias/$'
    | '/designs/$slug'
    | '/docs/$'
    | '/i/$'
    | '/u/$username'
  id:
    | '__root__'
    | '/'
    | '/designs'
    | '/developers'
    | '/docs'
    | '/downloads'
    | '/logo'
    | '/pitch'
    | '/pricing'
    | '/products'
    | '/$alias/$'
    | '/designs/$slug'
    | '/docs/$'
    | '/i/$'
    | '/u/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignsRoute: typeof DesignsRouteWithChildren
  DevelopersRoute: typeof DevelopersRoute
  DocsRoute: typeof DocsRouteWithChildren
  DownloadsRoute: typeof DownloadsRoute
  LogoRoute: typeof LogoRoute
  PitchRoute: typeof PitchRoute
  PricingRoute: typeof PricingRoute
  ProductsRoute: typeof ProductsRoute
  AliasSplatRoute: typeof AliasSplatRoute
  ISplatRoute: typeof ISplatRoute
  UUsernameRoute: typeof UUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitch': {
      id: '/pitch'
      path: '/pitch'
      fullPath: '/pitch'
      preLoaderRoute: typeof PitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logo': {
      id: '/logo'
      path: '/logo'
      fullPath: '/logo'
      preLoaderRoute: typeof LogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designs': {
      id: '/designs'
      path: '/designs'
      fullPath: '/designs'
      preLoaderRoute: typeof DesignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$': {
      id: '/i/$'
      path: '/i/$'
      fullPath: '/i/$'
      preLoaderRoute: typeof ISplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof DocsRoute
    }
    '/designs/$slug': {
      id: '/designs/$slug'
      path: '/$slug'
      fullPath: '/designs/$slug'
      preLoaderRoute: typeof DesignsSlugRouteImport
      parentRoute: typeof DesignsRoute
    }
    '/$alias/$': {
      id: '/$alias/$'
      path: '/$alias/$'
      fullPath: '/$alias/$'
      preLoaderRoute: typeof AliasSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DesignsRouteChildren {
  DesignsSlugRoute: typeof DesignsSlugRoute
}

const DesignsRouteChildren: DesignsRouteChildren = {
  DesignsSlugRoute: DesignsSlugRoute,
}

const DesignsRouteWithChildren =
  DesignsRoute._addFileChildren(DesignsRouteChildren)

interface DocsRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignsRoute: DesignsRouteWithChildren,
  DevelopersRoute: DevelopersRoute,
  DocsRoute: DocsRouteWithChildren,
  DownloadsRoute: DownloadsRoute,
  LogoRoute: LogoRoute,
  PitchRoute: PitchRoute,
  PricingRoute: PricingRoute,
  ProductsRoute: ProductsRoute,
  AliasSplatRoute: AliasSplatRoute,
  ISplatRoute: ISplatRoute,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
